name    'saz-supybot_irc'
version '1.0.0'
source 'UNKNOWN'
author 'saz'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'Report processor that notifies an IRC channel about failed Puppet runs via supybot, based on https://github.com/jamtur01/puppet-irc'
project_page 'https://github.com/saz/puppet-supybot_irc'
